import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="bg-black/95 text-white p-4 sm:p-15 sm:container mx-auto addTransition"
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
